"""Inventory Git and Jujutsu repositories below a directory."""

from vcs_tree.scanner import find_repo_roots, vcs_tree

__all__ = ["find_repo_roots", "vcs_tree"]
__version__ = "0.1.0"
from .delta import DeltaCalculator, HistoryDeltaCalculator
from .enrichment import EnrichmentResult, PulseEnricher
from .git_adapter import GitAdapter, GitObservation
from .jj_adapter import JjAdapter, JjObservation
from .ledger import (
    HistoryLedger,
    LedgerCorruptError,
    LedgerError,
    LedgerStatus,
    StatePaths,
    WriterMismatchError,
    resolve_paths,
)
from .models import (
    V2_REPOSITORY_COMPONENTS,
    Backend,
    Certainty,
    CollectionError,
    CollectionOutcome,
    CollectionState,
    ContractError,
    DeltaEnvelope,
    Event,
    Freshness,
    HistoryBoundary,
    HistoryBoundaryState,
    HistoryStore,
    IntegrityState,
    ObjectId,
    ObservationOutcome,
    Placement,
    PulseEnvelope,
    RefreshState,
    RepositoryMode,
    Retention,
    SnapshotEnvelope,
    SnapshotEnvelopeV2,
    WorkingCopyState,
    WriterPolicy,
    dumps,
    loads,
)
from .pulse import PulseOrchestrator, PulseSelectionError
from .snapshot import SnapshotCollector, SnapshotResult, discover_repository_roots
from .snapshot_schema import component_comparison, normalize_snapshot, parse_snapshot
from .temporal import (
    TEMPORAL_SCHEMA,
    TEMPORAL_SCHEMA_VERSION,
    AtomicFact,
    ComponentObservation,
    TemporalIndexBuilder,
    fact_key,
    fact_state,
)

__all__ = [
    "Backend",
    "Certainty",
    "CollectionError",
    "CollectionOutcome",
    "CollectionState",
    "ContractError",
    "DeltaEnvelope",
    "Event",
    "HistoryBoundary",
    "HistoryBoundaryState",
    "HistoryStore",
    "IntegrityState",
    "Freshness",
    "ObjectId",
    "ObservationOutcome",
    "PulseEnvelope",
    "Placement",
    "RepositoryMode",
    "RefreshState",
    "Retention",
    "SnapshotEnvelope",
    "SnapshotEnvelopeV2",
    "V2_REPOSITORY_COMPONENTS",
    "WorkingCopyState",
    "WriterPolicy",
    "dumps",
    "loads",
    "component_comparison",
    "normalize_snapshot",
    "parse_snapshot",
    "TEMPORAL_SCHEMA",
    "TEMPORAL_SCHEMA_VERSION",
    "AtomicFact",
    "ComponentObservation",
    "TemporalIndexBuilder",
    "fact_key",
    "fact_state",
    "HistoryLedger",
    "LedgerCorruptError",
    "LedgerError",
    "LedgerStatus",
    "StatePaths",
    "WriterMismatchError",
    "resolve_paths",
    "GitAdapter",
    "GitObservation",
    "JjAdapter",
    "JjObservation",
    "SnapshotCollector",
    "SnapshotResult",
    "discover_repository_roots",
    "DeltaCalculator",
    "HistoryDeltaCalculator",
    "PulseOrchestrator",
    "PulseSelectionError",
    "EnrichmentResult",
    "PulseEnricher",
]
